include:
  - ../compose.yaml

services:
  starter:
    build:
      context: .
      target: builder
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    volumes:
      - .:/go/app
    links:
      - temporal
    depends_on:
      worker:
        condition: service_started
      temporal:
        condition: service_healthy
    entrypoint: go
    command: run ./starter

  worker:
    build:
      context: .
      target: builder
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    volumes:
      - .:/go/app
    links:
      - temporal
    depends_on:
      temporal:
        condition: service_healthy
