name: Golang
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: golang
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./golang/go.mod

      - name: Test
        run: |
          go vet -v ./...
          go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ./golang
