name: Update README
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate readme
        run: |
          repo="${{ github.repository }}"

          REPO_OWNER="${repo%%/*}" REPO_NAME="${repo##*/}" make generate-readme

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "docs: update generated readme"
